### ISSUE TITLE
Can not find MX records for email option

### ISSUE THREAD

**Issue by SerafimArts** [kelunik/acme-client#3]
> ACME.ERROR: Kelunik\Acme\AcmeException: No MX record defined for 'yandex.ru' in ~/acme-client/src/Commands/Register.php:97

**Comment by SerafimArts** [comment]
Real error:

##### Connection to udp://2001:4860:4860::8844:53 failed: [Error #22] Invalid argument

```
#0 /home/downloads/acme-client/vendor/amphp/dns/lib/functions.php(155): Amp\Dns\__loadNewServer(Object(stdClass), 'udp://2001:4860...')
#1 /home/downloads/acme-client/vendor/amphp/dns/lib/functions.php(243): Amp\Dns\__doRequest(Object(stdClass), 'udp://2001:4860...', 'yandex.ru', 15)
#2 [internal function]: Amp\Dns\__doResolve('yandex.ru', Array, Array)
#3 /home/downloads/acme-client/vendor/amphp/amp/lib/functions.php(862): Generator->send(NULL)
#4 /home/downloads/acme-client/vendor/amphp/amp/lib/Success.php(25): Amp\__coroutineSend(NULL, NULL, Object(Amp\CoroutineState))
#5 /home/downloads/acme-client/vendor/amphp/amp/lib/functions.php(846): Amp\Success->when('Amp\\__coroutine...', Object(Amp\CoroutineState))
#6 /home/downloads/acme-client/vendor/amphp/amp/lib/NativeReactor.php(99): Amp\__coroutineNextTick('00000000619c03d...', Object(Amp\CoroutineState))
#7 /home/downloads/acme-client/vendor/amphp/amp/lib/NativeReactor.php(171): Amp\NativeReactor->tryImmediate(Object(stdClass))
#8 /home/downloads/acme-client/vendor/amphp/amp/lib/NativeReactor.php(70): Amp\NativeReactor->doTick(false)
#9 /home/downloads/acme-client/vendor/amphp/amp/lib/functions.php(46): Amp\NativeReactor->run(Object(Closure))
#10 /home/downloads/acme-client/bin/acme(101): Amp\run(Object(Closure))
#11 {main}
```

**Comment by kelunik** [comment]
This should be fixed by https://github.com/amphp/dns/commit/2f8103f1738fe48553b80733076c987234d8f49e, thanks for reporting.

Please try running `composer update` and repeat the command you executed.

**Comment by SerafimArts** [comment]
Yes, its works. Thx, have a nice day =)
