### ISSUE TITLE
Respect ACME rate limits to prevent renewal errors

### ISSUE THREAD

**Issue by FunkyM** [kelunik/acme-client#49]
With over 150 domains I am experiencing a few issue on renewal using the "auto" command:
```
...
Invalid response: .
Request URI: https://acme-v01.api.letsencrypt.org/acme/new-authz.
Invalid response: .
Request URI: https://acme-v01.api.letsencrypt.org/acme/new-authz.
exception 'Kelunik\Acme\AcmeException' with message 'Issuance failed, not all challenges could be solved.' in phar://acme-client/build/acme-client.phar/src/Commands/Issue.php:104



' in phar://acme-client/build/acme-client.phar/src/Commands/Auto.php:236
Stack trace:
#0 [internal function]: Kelunik\AcmeClient\Commands\Auto::checkAndIssue(Array, 'letsencrypt', '/etc/acme')
#1 phar://acme-client/build/acme-client.phar/vendor/amphp/amp/lib/functions.php(876): Generator->send(Object(stdClass))
#2 [internal function]: Amp\__coroutineSend(NULL, Object(stdClass), Object(Amp\CoroutineState))
#3 phar://acme-client/build/acme-client.phar/vendor/amphp/amp/lib/Placeholder.php(91): call_user_func('Amp\\__coroutine...', NULL, Object(stdClass), Object(Amp\CoroutineState))
#4 phar://acme-client/build/acme-client.phar/vendor/amphp/amp/lib/PrivatePromisor.php(20): Amp\PrivatePlaceholder->resolve(NULL, Object(stdClass))
#5 [internal function]: Amp\PrivatePlaceholder->Amp\{closure}(NULL, Object(stdClass))
#6 phar://acme-client/build/acme-client.phar/vendor/amphp/amp/lib/PrivatePromisor.php(57): call_user_func(Object(Closure), NULL, Object(stdClass))
#7 phar://acme-client/build/acme-client.phar/vendor/amphp/process/Process.php(106): Amp\Deferred->succeed(Object(stdClass))
#8 [internal function]: Amp\Process->Amp\{closure}('00000000511c7e9...', NULL)
#9 phar://acme-client/build/acme-client.phar/vendor/amphp/amp/lib/NativeReactor.php(100): call_user_func(Object(Closure), '00000000511c7e9...', NULL)
#10 phar://acme-client/build/acme-client.phar/vendor/amphp/amp/lib/NativeReactor.php(172): Amp\NativeReactor->tryImmediate(Object(stdClass))
#11 phar://acme-client/build/acme-client.phar/vendor/amphp/amp/lib/NativeReactor.php(71): Amp\NativeReactor->doTick(false)
#12 phar://acme-client/build/acme-client.phar/vendor/amphp/amp/lib/functions.php(46): Amp\NativeReactor->run(Object(Closure))
#13 phar://acme-client/build/acme-client.phar/bin/acme(170): Amp\run(Object(Closure))
#14 acme-client/build/acme-client.phar(2): include('phar:///root/Do...')
#15 {main}
```
To me it looks like I am hitting [rate limits](https://letsencrypt.org/docs/rate-limits/) and thus the invalid response is received?

I mentioned this briefly [before already](/kelunik/acme-client/issues/22#issuecomment-216506918).
It's nice that acme-client is asynchronous but I guess there is still an issue with that feature if you renew certs for many domains.

The following patch fixes it completely and all domains "auto" renew in one go just fine (although the overall process takes a bit longer with the patch, reliability is more important to me than super fast execution in a "90-day renewal timeframe"...):
```
diff --git a/src/Commands/Auto.php b/src/Commands/Auto.php
index 974280e..9a8082f 100644
--- a/src/Commands/Auto.php
+++ b/src/Commands/Auto.php
@@ -119,16 +119,13 @@ class Auto implements Command {
         $values = [];
 
         foreach ($certificateChunks as $certificateChunk) {
-            $promises = [];
-
             foreach ($certificateChunk as $certificate) {
+                $promises = [];
                 $promises[] = \Amp\resolve($this->checkAndIssue($certificate, $config["server"], $config["storage"]));
+                list($chunkErrors, $chunkValues) = (yield \Amp\any($promises));
+                $errors += $chunkErrors;
+                $values += $chunkValues;
             }
-
-            list($chunkErrors, $chunkValues) = (yield \Amp\any($promises));
-
-            $errors += $chunkErrors;
-            $values += $chunkValues;
         }
 
         $status = [
diff --git a/src/Commands/Issue.php b/src/Commands/Issue.php
index 864fdd2..79fbc4b 100644
--- a/src/Commands/Issue.php
+++ b/src/Commands/Issue.php
@@ -85,15 +85,12 @@ class Issue implements Command {
         $domainChunks = array_chunk($domains, 10, true);
 
         foreach ($domainChunks as $domainChunk) {
-            $promises = [];
-
             foreach ($domainChunk as $i => $domain) {
+                $promises = [];
                 $promises[] = \Amp\resolve($this->solveChallenge($acme, $keyPair, $domain, $docRoots[$i]));
+                list($chunkErrors) = (yield \Amp\any($promises));
+                $errors += $chunkErrors;
             }
-
-            list($chunkErrors) = (yield \Amp\any($promises));
-
-            $errors += $chunkErrors;
         }
 
         if (!empty($errors)) {
```

**Comment by kelunik** [comment]
Dunno, 10 * 10 = 100 pending challenges should be fine for Let's Encrypt. Anyway, I agree and I changed the certificates to be sequential and added a flag to `issue` that allows controlling the concurrency. I corresponding config key named `challenge-concurrency` has also been added. I don't have much time right now, so all these changes are untested right now. I'd be glad if you could test them, they're rather small, so I don't expect anything to be broken.

**Comment by FunkyM** [comment]
Thanks, will test and report back.

**Comment by kelunik** [comment]
@FunkyM Did you have time to test it?

**Comment by FunkyM** [comment]
@kelunik Yes, I did test it. It only passed fine with `challenge-concurrency = 1`.
I noticed that despite DNS etc. didn't fail anymore it broke with "Invalid Response: .".
It kind of looks to me that the ACME servers kind of tell you "please try again" but acme-client is erroring out instead of retrying.
Anyways, I will try to debug exactly what kind of response is retrieved that causes things to fail next before actually giving the green light on this.

**Comment by kelunik** [comment]
> I noticed that despite DNS etc. didn't fail anymore it broke with "Invalid Response: .".

Yes, knowing which response it actually received would be really helpful.

**Comment by kelunik** [comment]
@FunkyM Please comment if you have more info.
