### ISSUE TITLE
Call to undefined function idn_to_ascii

### ISSUE THREAD

**Issue by feamsr00** [kelunik/acme-client#58]
Hi There,

This might be a (simple?) issue with an upstream project but I'll report it where I found it :)

```
C:\exec>acme-client issue -d sso.<DOMAIN> -p C:\exec\Crowd\crowd-webapp

    Providing payload at http://sso.<DOMAIN>/.well-known/acme-challenge/<CHALLANGE>

Fatal error: Uncaught Error: Call to undefined function idn_to_ascii() in phar://C:/exec/acme-client.phar/vendor/amphp/artax/lib/Cookie/PublicSuffixList.php:76
Stack trace:
#0 phar://C:/exec/acme-client.phar/vendor/amphp/artax/lib/Cookie/PublicSuffixList.php(61): Amp\Artax\Cookie\PublicSuffixList::toRegex('a\xC3\xA9roport.ci', false)
#1 phar://C:/exec/acme-client.phar/vendor/amphp/artax/lib/Cookie/PublicSuffixList.php(13): Amp\Artax\Cookie\PublicSuffixList::readList()
#2 phar://C:/exec/acme-client.phar/vendor/amphp/artax/lib/Client.php(666): Amp\Artax\Cookie\PublicSuffixList::isPublicSuffix('<DOMAIN>')
#3 phar://C:/exec/acme-client.phar/vendor/amphp/artax/lib/Client.php(531): Amp\Artax\Client->storeResponseCookie('sso.<DOMAIN>', '__cfduid=d9dfb8...')
#4 phar://C:/exec/acme-client.phar/vendor/amphp/artax/lib/Client.php(489): Amp\Artax\Client->assignParsedResponse(Object(Amp\Artax\RequestCycle), Array)
#5 phar://C:/exec/acme-client.phar/vendor/amphp/artax/lib/Client.php(476): Amp\Artax\Client->parseSocketData(Object(A in phar://C:/exec/acme-client.phar/vendor/amphp/artax/lib/Cookie/PublicSuffixList.php on line 76
```

So `amphp/artax` appears to rely on the intl extension. Is this a known requirement of this project? If not, can this exception be trapped and handled accordingly? If it is a requirement, perhaps a better message is in order. Regardless, it's a good error handling policy to trap and convert *known* exceptions to sane and useful error messages.

```
C:\exec>acme-client version
Γöî kelunik/acme-client @ 0.2.14 (built: May 10th 2017 08:32:52 UTC)
Γöö Let's Encrypt / ACME client written in PHP for the CLI.

C:\exec>php -v
PHP 7.1.3 (cli) (built: Mar 14 2017 23:33:39) ( ZTS MSVC14 (Visual C++ 2015) x64 )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
```

**Comment by kelunik** [comment]
It is a known requirement that's supposed to be not there, but with the lastest version it should just work fine, as Cookies should be disabled by default there.

**Comment by kelunik** [comment]
I'll close this issue for now. There won't be a new version of Artax v2 that fixes it, but it will be fixed with the move to Artax v3.

**Comment by feamsr00** [comment]
Thanks for the heads up. ETA on Artax v3?

**Comment by kelunik** [comment]
Artax v3 is already released, as is `kelunik/acme`, just the client is missing now. I can't promise any ETA right now.

**Comment by kelunik** [comment]
Alpha versions of 0.3.0 have been released now.
